CREATE TABLE Rescue
(
	RescueID VARCHAR (20) PRIMARY KEY,
	Date DATE NOT NULL,
	Location VARCHAR(100) NOT NULL,
	GA INTEGER NOT NULL,
	AnimalBreed VARCHAR(100) NOT NULL,
	AnimalName VARCHAR(100) NOT NULL,
	AnimalWeight FLOAT NOT NULL,
	AnimalSuperfamily VARCHAR(100) NOT NULL
);